# Generated by Django 3.1.5 on 2021-01-19 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GuestbookEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(verbose_name='date entered')),
                ('entry_name', models.CharField(max_length=100)),
                ('entry_fav_pkmn', models.CharField(max_length=100)),
                ('entry_fav_joke', models.CharField(max_length=500)),
                ('entry_blurb', models.CharField(max_length=400, verbose_name="Anything you'd like to say?")),
            ],
        ),
    ]
