# Generated by Django 3.1.5 on 2021-01-20 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0002_auto_20210119_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestbookentry',
            name='entry_picture',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
