# Generated by Django 3.1.5 on 2021-03-03 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0004_auto_20210201_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookentry',
            name='entry_picture',
            field=models.ImageField(default='../media/rickastley.png', upload_to='uploads/'),
        ),
    ]
