# Generated by Django 3.1.5 on 2021-03-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guestbook', '0005_auto_20210302_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guestbookentry',
            name='entry_blurb',
            field=models.CharField(blank=True, max_length=400, verbose_name="Anything else you'd like to say?"),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='entry_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Entered'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='entry_fav_joke',
            field=models.CharField(blank=True, max_length=500, verbose_name='Tell me your favourite joke!'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='entry_fav_pkmn',
            field=models.CharField(blank=True, max_length=100, verbose_name='What is your favourite Pokemon?'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='entry_name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='guestbookentry',
            name='entry_picture',
            field=models.ImageField(blank=True, upload_to='uploads/', verbose_name='Want to include a picture?'),
        ),
    ]
